name: Docker Image Build

on: push

jobs:
  dockerimage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Build the base image
        run: docker build . --file Dockerfile --tag trailofbits/polytracker --no-cache
