name: Integration Tests

on: [pull_request, workflow_dispatch]

jobs:
  # TODO: Consider building the base image as a separate job and caching the result
  integration_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        example: [mupdf,poppler,qpdf]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Build the base Polytracker Docker image
        run: docker build . --file Dockerfile --tag trailofbits/polytracker --no-cache
      - name: Build the example Docker image
        run: docker build --no-cache examples --file examples/Dockerfile-${{ matrix.example }}.demo --tag trailofbits/polytracker-demo-${{ matrix.example }}
      - name: PolyTracker tests
        run: docker run --rm trailofbits/polytracker pytest
