on: pull_request

jobs:
  integration_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the base image
        run: docker build . --file Dockerfile --tag trailofbits/polytracker --no-cache
      - name: Build the mupdf demo Docker image
        run: docker build examples --file examples/Dockerfile-mupdf.demo --tag trailofbits/polytracker-demo-mupdf
      - name: Build the poppler demo Docker image
        run: docker build examples --file examples/Dockerfile-poppler.demo --tag trailofbits/polytracker-demo-poppler
      - name: Build the qpdf demo Docker image
        run: docker build examples --file examples/Dockerfile-qpdf.demo --tag trailofbits/polytracker-demo-qpdf
